const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const db=require('pg-mem').newDb();db.public.none(fs.readFileSync(path.join(__dirname,'../schema.sql'),'utf8'));
const {Pool}=db.adapters.createPg(),pool=new Pool();
pool.withTransaction=async fn=>{const backup=db.backup();try{return await fn(pool);}catch(e){backup.restore();throw e;}};
const stub=(p,exports)=>require.cache[require.resolve(p)]={exports};
stub('../src/config/db',pool);stub('../src/config/redis',new(require('ioredis-mock'))());
stub('../src/services/sms.service',{sendOrderNotification:async()=>true});
stub('../src/services/translation.service',{translateOrder:async()=>null});
const calls=[];stub('axios',{post:async(url,body)=>{calls.push({url,body});return {data:{ok:true,result:{message_id:1}}};}});
const categories=require('../src/services/category.service'),masters=require('../src/services/master.service'),orders=require('../src/services/order.service'),telegram=require('../src/services/telegram.service'),dispatch=require('../src/services/dispatch.service');
const definition={name_ru:'Сантехник',name_ka:'სანტექნიკოსი',name_en:'Plumber',icon:'🔧',is_active:true,fields:[{input:'text',name_ru:'Опыт',name_ka:'გამოცდილება',name_en:'Experience',required:true}]};
(async()=>{
 const initial=await categories.list();assert.equal(initial.length,5);
 const category=await categories.save(null,definition),key=category.slug,field=category.fields[0].key;
 assert.ok((await categories.groups())[key].includes('Сантехник'));
 assert.equal((await categories.configForView('en')).find(c=>c.type===key).label,'Plumber');
 const member=await masters.registerMaster({name:'Plumber',phone:'+995500000909',description:'Plumbing',serviceType:null});
 const profile={name:member.name,phone:member.phone,description:'Plumbing',category:key,serviceAttributes:{[field]:'5 years'}};
 await assert.rejects(masters.updateMasterProfile(member.id,{...profile,serviceAttributes:{}}),{code:'INVALID_SERVICE'});
 await masters.updateMasterProfile(member.id,profile);await masters.approveMaster(member.id);
 await pool.query('UPDATE masters SET balance_tetri=500 WHERE id=$1',[member.id]);
 assert.equal((await masters.listMasters({serviceType:key})).length,1);
 const order=(await pool.query("INSERT INTO orders(token,phone,description,status) VALUES('catorder','+995500000908','Plumbing','pending_review') RETURNING *")).rows[0];
 const keyboard=await telegram.buildKeyboardWithCounts(order.token);
 const button=keyboard.inline_keyboard.flat().find(b=>b.text.includes('Сантехник'));
 assert.ok(button.callback_data.includes(key));assert.ok(button.text.includes('(1)'));
 for(const b of keyboard.inline_keyboard.flat()) if(b.callback_data) assert.ok(Buffer.byteLength(b.callback_data)<=64);
 const plan=await dispatch.preview(order.token,key,'');assert.equal(plan.count,1);
 const result=await dispatch.dispatch(order.token,key,'',{price:plan.price,count:plan.count,revision:0});assert.equal(result.count,1);
 assert.equal((await pool.query('SELECT balance_tetri FROM masters WHERE id=$1',[member.id])).rows[0].balance_tetri,450);
 await assert.rejects(dispatch.dispatch(order.token,key,''));
 const off=await categories.save(key,{...definition,version:category.version,is_active:false,fields:definition.fields.map(f=>({...f,key:field}))});
 assert.equal((await orders.getDispatchRecipients(key,'',50)).length,0);
 await assert.rejects(dispatch.preview(order.token,key,''));
 assert.equal((await masters.listMasters({serviceType:key})).length,0);
 assert.ok(!(await telegram.buildKeyboardWithCounts(order.token)).inline_keyboard.flat().some(b=>b.callback_data?.includes(key)));
 assert.equal((await pool.query('SELECT * FROM master_services WHERE master_id=$1',[member.id])).rows.length,1);
 assert.equal((await pool.query('SELECT * FROM order_dispatches WHERE order_id=$1',[order.id])).rows.length,1);
 await assert.rejects(categories.save(key,{...definition,version:1,fields:definition.fields.map(f=>({...f,key:field}))}),{status:409});
 const on=await categories.save(key,{...definition,version:off.version,fields:definition.fields.map(f=>({...f,key:field}))});assert.ok(on.is_active);
 process.env.TELEGRAM_BOT_TOKEN='test-only';process.env.NODE_ENV='test';
 await telegram.refreshCategories(order,'100',200);
 assert.ok(calls.at(-1).body.reply_markup.inline_keyboard.flat().some(b=>b.callback_data?.includes(key)));
 await telegram.refreshCategories({...order,status:'closed'},'100',200);assert.deepEqual(calls.at(-1).body.reply_markup.inline_keyboard,[]);
 const ejs=require('ejs'),views=path.join(__dirname,'../src/views/admin');
 for(const file of ['categories.ejs','category-edit.ejs']) {
  const html=ejs.render(fs.readFileSync(path.join(views,file),'utf8'),{categories:await categories.list(),category:on,submitted:null,error:null,csrfToken:'csrf',fieldsLocked:categories.hasLockedField(on.fields)},{filename:path.join(views,file),includer:(original,parsed)=>original==='./_header'||original==='./_footer'?{template:''}:{filename:parsed}});
  for(const script of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(script[1]);
 }
 await assert.rejects(categories.save(null,{...definition,name_ru:''}),{status:400});
 await assert.rejects(categories.save(null,{...definition,fields:[{...definition.fields[0],key:'__proto__'}]}),{status:400});
 console.log('PASS: category creation, translations, attributes, assignment, catalog, Telegram buttons, paid dispatch, disabled stale buttons, history, refresh and optimistic concurrency');
})().catch(e=>{console.error(e);process.exitCode=1;});
