const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const db=require('pg-mem').newDb();db.public.none(fs.readFileSync(path.join(__dirname,'../schema.sql'),'utf8'));
const {Pool}=db.adapters.createPg(),pool=new Pool();
pool.withTransaction=async fn=>{const backup=db.backup();try{return await fn(pool);}catch(e){backup.restore();throw e;}};
const stub=(name,exports)=>require.cache[require.resolve(name)]={exports};
stub('../src/config/db',pool);const redis=new(require('ioredis-mock'))();stub('../src/config/redis',redis);
let sends=0,fail=false,tgWorks=false;
stub('../src/services/sms.service',{sendOrderNotification:async(phone,text)=>{sends++;if(fail)throw Object.assign(Error('gateway rejected'),{deliveryUnknown:false});return {ok:true,status:'accepted',providerMessageId:'sms-123',providerResponse:'OK: 123456',messageBody:text};}});
stub('../src/services/telegram.service',{sendLeadToMaster:async()=>tgWorks?{ok:true,providerMessageId:'tg-123',providerResponse:{ok:true},messageBody:'Telegram lead'}:false,sendToChat:async()=>{}});
const orders=require('../src/services/order.service'),audit=require('../src/services/consentLog.service');
(async()=>{
 const master=(await pool.query("INSERT INTO masters(name,phone,master_token,category,is_active,is_subscribed,balance_tetri) VALUES('Test','+995500000222','test','movers',true,true,5000) RETURNING *")).rows[0];
 await pool.query("INSERT INTO master_services(master_id,service_type,attributes,is_primary) VALUES($1,'movers','{}',true)",[master.id]);
 await require('./billing-fixture')(pool,master.id);
 const create=async token=>(await pool.query("INSERT INTO orders(token,phone,description,status,target_categories) VALUES($1,'+995500000333','Move boxes','new',ARRAY['movers','transport']) RETURNING *",[token])).rows[0];
 const balance=async()=>Number((await pool.query('SELECT balance_tetri FROM masters WHERE id=$1',[master.id])).rows[0].balance_tetri);
 const count=async order=>Number((await pool.query("SELECT count(*) FROM balance_transactions WHERE order_id=$1 AND reason='lead_charge'",[order.id])).rows[0].count);
 const first=await create('first');
 assert.equal(await orders.notifyMasters(first,'movers',null,50),1);assert.equal(await balance(),4950);
 let evidence=(await pool.query("SELECT * FROM sms_consent_logs WHERE event_type='LEAD_CHARGE_ACCEPTED' AND order_id=$1",[first.id])).rows[0];
 assert.equal(evidence.metadata.amount_tetri,50);assert.equal(evidence.metadata.provider_message_id,'sms-123');
 assert.equal(evidence.metadata.channel,'sms');assert.equal(evidence.metadata.delivery_status,'unknown');
 const transaction=(await pool.query('SELECT * FROM balance_transactions WHERE id=$1',[evidence.metadata.balance_transaction_id])).rows[0];
 assert.equal(transaction.amount_tetri,-50);assert.equal(transaction.order_id,first.id);
 const before=sends;assert.equal(await orders.notifyMasters(first,'movers',null,100),0);
 assert.equal(sends,before);assert.equal(await count(first),1);assert.equal(await balance(),4950);
 const rejected=await create('rejected');fail=true;
 assert.equal(await orders.notifyMasters(rejected,'movers',null,50),0);assert.equal(await count(rejected),0);assert.equal(await balance(),4950);
 assert.equal((await pool.query('SELECT status FROM dispatch_deliveries WHERE order_id=$1',[rejected.id])).rows[0].status,'failed');
 fail=false;const original=audit.recordAction;
 audit.recordAction=async args=>{if(args.eventType==='LEAD_CHARGE_ACCEPTED')throw Error('audit unavailable');};
 assert.equal(await orders.notifyMasters(rejected,'movers',null,50),0);
 assert.ok((await pool.query("SELECT * FROM dispatch_deliveries WHERE order_id=$1 AND status='pending'",[rejected.id])).rows.length);
 assert.equal(await count(rejected),0);assert.equal(await balance(),4950,'charge rolls back with missing evidence');
 audit.recordAction=original;
 assert.equal(await orders.notifyMasters(rejected,'movers',null,50),0);assert.equal(await count(rejected),0,'uncertain delivery is not retried automatically');
 const closed=await create('closed');await orders.closeOrder(closed.token);
 let sentBefore=sends;assert.equal(await orders.notifyMasters(closed,'movers',null,50),0);assert.equal(sends,sentBefore);
 const partial=await create('partial');await orders.closeOrderCategory(partial.token,'movers');
 assert.equal(await orders.notifyMasters(partial,'movers',null,50),0);assert.equal(await count(partial),0);
 tgWorks=true;await pool.query("UPDATE masters SET telegram_id='123' WHERE id=$1",[master.id]);
 const telegram=await create('telegram');sentBefore=sends;
 assert.equal(await orders.notifyMasters(telegram,'movers',null,50),1);assert.equal(sends,sentBefore);
 evidence=(await pool.query("SELECT metadata FROM sms_consent_logs WHERE event_type='LEAD_CHARGE_ACCEPTED' AND order_id=$1",[telegram.id])).rows[0].metadata;
 assert.equal(evidence.channel,'telegram');assert.equal(evidence.provider_message_id,'tg-123');
 tgWorks=false;const fallback=await create('fallback');assert.equal(await orders.notifyMasters(fallback,'movers',null,50),1);assert.equal(sends,sentBefore+1);
 console.log('PASS: receipts tied to charges, no duplicate debits, rejection, atomic audit rollback, closed requests, Telegram and SMS fallback');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>redis.disconnect());
