const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const db=require('pg-mem').newDb();db.public.none(fs.readFileSync(path.join(__dirname,'../schema.sql'),'utf8'));
const {Pool}=db.adapters.createPg(),pool=new Pool();
pool.withTransaction=async fn=>{const backup=db.backup();try{return await fn(pool);}catch(e){backup.restore();throw e;}};
const stub=(p,exports)=>require.cache[require.resolve(p)]={exports};
stub('../src/config/db',pool);const redis=new(require('ioredis-mock'))();stub('../src/config/redis',redis);
stub('../src/services/telegram.service',{updateMessage:async()=>{},sendToChat:async()=>{},sendLeadToMaster:async()=>false});
stub('../src/services/sms.service',{sendOrderNotification:async()=>({ok:true,providerMessageId:'test'})});
stub('../src/services/translation.service',{translateOrder:async()=>null,detectLang:()=> 'ru'});
process.env.ADMIN_PASSWORD='test-only';process.env.ADMIN_SESSION_SECRET='multi-service-ui-only';
const auth=require('../src/config/adminAuth'),session=auth.createSessionValue();
const masters=require('../src/services/master.service'),orders=require('../src/services/order.service');
let server;
(async()=>{
 const m=await masters.registerMaster({name:'Демо исполнитель',phone:'+995500009111',serviceType:null});
 const o=(await pool.query("INSERT INTO orders(token,owner_token,phone,description,status) VALUES('ui-multi','ui-owner','+995500009222','Переезд: машина и два грузчика','pending_review') RETURNING *")).rows[0];
 const express=require('express'),app=express();app.set('view engine','ejs');app.set('views',path.join(__dirname,'../src/views'));
 app.use(express.urlencoded({extended:false}));app.use(require('cookie-parser')());
 if(process.env.PREVIEW_MULTISERVICE)app.use((req,res,next)=>{req.cookies.admin_session=session.cookieValue;next();});
 app.use(express.static(path.join(__dirname,'../public')));
 app.use('/admin',require('../src/routes/admin.routes'));
 const manager=(await pool.query("INSERT INTO managers(name,phone,is_moderator) VALUES('Демо менеджер','+995500009333',true) RETURNING *")).rows[0];
 const pending=await masters.registerMaster({name:'Демо новый исполнитель',phone:'+995500009444',serviceType:null});
 app.get('/preview-manager',async(req,res,next)=>{try{
  const locals=await require('../src/services/managerPortal.service').reviewGet(manager.id,pending.id);
  res.render('manager/review',{...locals,manager,csrf:'test',date:v=>String(v)});
 }catch(e){next(e);}});
 app.use((e,req,res,next)=>{console.error(e);res.status(500).send(e.message);});
 server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
 const base='http://127.0.0.1:'+server.address().port;
 const cookie='admin_session='+session.cookieValue;
 const get=async url=>{const response=await fetch(base+url,{headers:{cookie}});assert.equal(response.status,200);const html=await response.text();for(const script of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(script[1]);return html;};
 const post=async(url,pairs)=>fetch(base+url,{method:'POST',headers:{cookie,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams([['_csrf',session.csrfToken],...pairs]),redirect:'manual'});
 const profilePage=await get('/admin/masters/'+m.id);
 assert.match(profilePage,/Какие услуги выполняет специалист/);
 assert.match(profilePage,/Каталог: действия заказчиков/);
 assert.match(profilePage,/Батуми · выключен/);
 assert.match(profilePage,/name="spokenLanguages"/);
 assert.match(profilePage,/Добавить новую услугу и её характеристики/);
 assert.match(await get('/admin/categories/new?returnTo=%2Fadmin%2Fmasters%2F'+m.id+'%23admin-services'),/Карточка специалиста/);
 assert.equal((await post('/admin/masters/'+m.id+'/update',[['name',m.name],['phone',m.phone],['cityIds','1'],['spokenLanguages','ru'],['servicesForm','1'],['services','van'],['services','movers'],['van_body','closed'],['vehicleSize','L'],['movers_crew_size','1'],['moversOwnTransport','on'],['thenApprove','1']])).status,302);
 assert.equal((await pool.query('SELECT * FROM master_services WHERE master_id=$1',[m.id])).rows.length,2);
 await pool.query('UPDATE masters SET balance_tetri=5000 WHERE id=$1',[m.id]);await require('./billing-fixture')(pool,m.id);
 await post('/admin/orders/ui-multi/needs',[['needs','transport'],['needs','movers'],['transportSize','L']]);
 const configured=await orders.getOrderByToken(o.token);assert.deepEqual(configured.target_categories,['transport','movers']);assert.equal(configured.requirements.transport_size,'L');
 const adminOrderPage=await get('/admin/orders/ui-multi');assert.match(adminOrderPage,/Что нужно клиенту/);
 // Страница заявки у администратора — тот же экран, что у менеджера, со своими адресами форм.
 assert.match(adminOrderPage,/name="transportSize" value="L" checked/);assert.match(adminOrderPage,/<b>L<\/b> — кузов от Д380×Ш180×В180 см/);
 assert.match(adminOrderPage,/name="needAttributes\[junk\]\[dump_body\]"[^>]*> Нужен самосвал/);
 assert.match(adminOrderPage,/action="\/admin\/orders\/ui-multi\/send" data-preview="\/admin\/orders\/ui-multi\/preview"/);
 assert.ok(!adminOrderPage.includes('/manager/orders'),'на странице администратора нет адресов кабинета менеджера');
 assert.match(adminOrderPage,/Только для администратора/);assert.match(adminOrderPage,/Вернуть заказчику на доработку/);assert.match(adminOrderPage,/Удалить заявку/);
 const adminPlan=await (await post('/admin/orders/ui-multi/preview',[['needs','transport'],['needs','movers'],['transportSize','L']])).json();
 assert.deepEqual([adminPlan.total,adminPlan.services.map(s=>s.key),adminPlan.services[0].sizes.find(s=>s.code==='L').count],[1,['transport','movers'],1]);
 assert.equal((await fetch(base+'/admin/orders/ui-multi/preview',{method:'POST',headers:{cookie,'content-type':'application/x-www-form-urlencoded'},body:'needs=transport'})).status,403,'без защитного кода формы расчёт не отдаётся');
 assert.match(await get('/admin/orders/ui-multi/dispatch?category=transport&size=L'),/Получателей с достаточным балансом/);
 const plan=await require('../src/services/dispatch.service').preview(o.token,'transport','L');
 const sent=await post('/admin/orders/ui-multi/dispatch',[['category','transport'],['size','L'],['price',String(plan.price)],['count',String(plan.count)],['revision',String(configured.revision_version)]]);
 assert.equal(sent.status,200);assert.match(await sent.text(),/Сообщений принято каналом/);
 const afterSend=await get('/admin/orders/ui-multi');
 assert.match(afterSend,/Отправки и отклики/);assert.match(afterSend,/Кто получил заявку и сколько списано/);
 assert.match(afterSend,/<a href="\/admin\/masters\/\d+">Демо исполнитель<\/a><\/td><td>\+995500009111/);
 // Уточнение и карточка — теми же кнопками, что у менеджера; автор в журнале — администратор.
 assert.equal((await post('/admin/orders/ui-multi/note',[['note','3 этаж без лифта']])).headers.get('location'),'/admin/orders/ui-multi');
 assert.equal((await orders.getOrderByToken(o.token)).manager_note,'3 этаж без лифта');
 assert.equal((await pool.query("SELECT metadata FROM sms_consent_logs WHERE order_id=$1 AND event_type='ORDER_CLARIFIED_BY_MANAGER'",[o.id])).rows[0].metadata.actor,'admin');
 assert.ok((await post('/admin/orders/ui-multi/text',[['description','Новый текст заявки после рассылки']])).headers.get('location').includes('?error='),'после рассылки текст не переписывается');
 assert.ok((await post('/admin/orders/ui-multi/brief',[['action','share']])).headers.get('location').includes('?error='),'карточки ещё нет');
 const stale=await post('/admin/orders/ui-multi/needs',[['needs','movers']]);assert.ok(stale.headers.get('location').includes('dispatchError='));
 const managerPage=await get('/preview-manager');
 assert.match(managerPage,/Сохранить услуги/);
 assert.match(managerPage,/Батуми · выключен/);
 assert.match(managerPage,/name="spokenLanguages"/);
 assert.match(managerPage,/name="van_cargo_length_cm"/);
 assert.match(managerPage,/<select name="vehicleSize"/);
 assert.match(managerPage,/name="junk_body_length_cm"/);
 assert.match(managerPage,/<input type="checkbox" name="junk_dump_body" > Самосвал — кузов поднимается и сам высыпает груз/);
 assert.ok(!managerPage.includes('vehicle_kind'),'the retired vehicle kind list is gone');
 const junkBody=require('../src/config/junkBody');
 assert.equal(junkBody.derive(400,200,100).tier,'8');
 assert.equal(junkBody.derive(199,100,100),null);
 const junk=await masters.registerMaster({name:'Самосвал',phone:'+995500009666',serviceType:null});
 await masters.updateMasterProfile(junk.id,{name:junk.name,phone:junk.phone,services:[{type:'junk',attributes:{body_length_cm:'400',body_width_cm:'200',side_height_cm:'100',payload_t:'5'}}]});
 const junkAttrs=(await pool.query("SELECT attributes FROM master_services WHERE master_id=$1 AND service_type='junk'",[junk.id])).rows[0].attributes;
 assert.equal(junkAttrs.volume_m3,'8');assert.equal(junkAttrs.body_length_cm,400);assert.equal(junkAttrs.payload_t,5);
 assert.equal(require('../src/services/serviceRequirements.service').matches(junkAttrs,{payload_t:4},[{key:'payload_t',input:'number',match:'gte'}]),true);
 await assert.rejects(()=>masters.updateMasterProfile(junk.id,{name:junk.name,phone:junk.phone,services:[{type:'junk',attributes:{body_length_cm:'400',volume_m3:'8'}}]}),{code:'INVALID_SERVICE'});
 const portal=require('../src/services/managerPortal.service');
 await portal.assignCategory(manager.id,pending.id,'van',{},'L',[{type:'van',attributes:{body:'closed'}},{type:'movers',attributes:{crew_size:2},requiresOwnTransport:true}]);
 const saved=await portal.reviewGet(manager.id,pending.id);assert.equal(saved.master.services.length,2);
 await pool.query('UPDATE masters SET manager_id=$2 WHERE id=$1',[m.id,manager.id]);
 await portal.assignCategory(manager.id,m.id,'van',{},'M',[{type:'van',attributes:{body:'closed'}}]);
 const updated=await portal.reviewGet(manager.id,m.id);
 assert.equal(updated.master.is_active,true);
 assert.equal(updated.master.services.length,1);
 assert.equal(updated.master.vehicle_size,'M');
 const stranger=(await pool.query("INSERT INTO managers(name,phone) VALUES('Чужой менеджер','+995500009555') RETURNING id")).rows[0].id;
 await assert.rejects(()=>portal.assignCategory(stranger,m.id,'van',{},'L',[{type:'van',attributes:{body:'closed'}}]),{status:403});
 await assert.rejects(()=>portal.requireHeadModerator(manager.id),{status:403});
 await pool.query('UPDATE managers SET is_head_moderator=true WHERE id=$1',[manager.id]);
 await portal.requireHeadModerator(manager.id);
 // Экран менеджера по заявке: услуги списком с расчётом «кто получит», одна кнопка отправки.
 const managerHtml=await require('ejs').renderFile(path.join(__dirname,'../src/views/manager/order-dispatch.ejs'),{
  ...await require('../src/services/dispatch.service').screen(o.token),manager:{...manager,is_head_moderator:true},csrf:'test',result:null,error:null,date:v=>String(v),money:v=>String(v),
 });
 assert.match(managerHtml,/Что нужно клиенту и кто получит заявку/);
 assert.match(managerHtml,/<input type="checkbox" name="needAttributes\[junk\]\[dump_body\]"[^>]*> Нужен самосвал/);
 assert.match(managerHtml,/Ставьте, только если в заявке прямо просят самосвал/);
 assert.match(managerHtml,/> Нужна машина с грузчиками<\/label>/,'требования перевозки названы от лица заказчика');
 assert.ok(!managerHtml.includes('data-service="flatbed"'),'отдельной строки «бортовая» в новых заявках нет: это «Перевозки» с типом кузова');
 assert.match(managerHtml,/<input type="checkbox" name="needs" value="transport" checked disabled data-fixed>/,'разосланная услуга отмечена и не снимается');
 assert.match(managerHtml,/<input type="checkbox" name="transportSize" value="L" checked disabled data-fixed>/,'разосланный класс кузова не снимается');
 assert.match(managerHtml,/<input type="checkbox" name="transportSize" value="XL"  >/,'другой класс можно добавить');
 assert.match(managerHtml,/name="transportAny"/,'ограничение по классу можно снять');
 assert.match(managerHtml,/Отправки и отклики/);
 assert.match(managerHtml,/Демо исполнитель \(#\d+\) · Принято каналом/,'в отправках имена и статусы по-русски');
 for(const script of managerHtml.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(script[1]);
 assert.equal((await pool.query('SELECT vehicle_size FROM masters WHERE id=$1',[m.id])).rows[0].vehicle_size,'M');
 // Три размера кузова в карточке администратора: букву ставит система, выбранная вручную не действует.
 assert.equal((await post('/admin/masters/'+m.id+'/update',[['name',m.name],['phone',m.phone],['cityIds','1'],['spokenLanguages','ru'],['servicesForm','1'],['services','van'],['van_body','closed'],['van_cargo_length_cm','280'],['van_cargo_width_cm','170'],['van_cargo_height_cm','170'],['vehicleSize','XL']])).headers.get('location'),'/admin/masters/'+m.id);
 const measuredPage=await get('/admin/masters/'+m.id);
 assert.match(measuredPage,/Кузов: <b>M · Д280×Ш170×В170 см<\/b>/);
 assert.match(measuredPage,/name="van_cargo_width_cm" data-van-cm min="1" max="2000" step="1" value="170"/);
 assert.ok((await post('/admin/masters/'+m.id+'/update',[['name',m.name],['phone',m.phone],['cityIds','1'],['spokenLanguages','ru'],['servicesForm','1'],['services','van'],['van_body','closed'],['van_cargo_length_cm','280']])).headers.get('location').endsWith('error=service_required'));
 assert.match(await get('/admin/masters'),/кузов <b class="text-stone-800">M · Д280×Ш170×В170 см<\/b>/);
 // Вторая машина исполнителя приходит полями van_more_<номер>_*; подпись показывает обе.
 assert.equal((await post('/admin/masters/'+m.id+'/update',[['name',m.name],['phone',m.phone],['cityIds','1'],['spokenLanguages','ru'],['servicesForm','1'],['services','van'],['van_body','closed'],['van_cargo_length_cm','280'],['van_cargo_width_cm','170'],['van_cargo_height_cm','170'],['vehicleSize',''],
  ['van_more_1_cargo_length_cm','400'],['van_more_1_cargo_width_cm','200'],['van_more_1_cargo_height_cm','200'],['van_more_1_size',''],['van_more_1_body','flatbed'],['van_more_1_tail_lift','on']])).headers.get('location'),'/admin/masters/'+m.id);
 const fleetPage=await get('/admin/masters/'+m.id);
 assert.match(fleetPage,/Кузов: <b>M · Д280×Ш170×В170 см; XL · Д400×Ш200×В200 см · борт<\/b>/);
 assert.match(fleetPage,/name="van_more_1_cargo_height_cm" data-van-cm min="1" max="2000" step="1" value="200"/);
 assert.match(fleetPage,/\+ Добавить машину/);
 // Пороги S…XXL сохраняются своей формой. Форму внутри формы браузер игнорирует: кнопка порогов отправляла форму категории, а кнопка категории оставалась без формы.
 const vanPage=await get('/admin/categories/van'),categoryForm=vanPage.indexOf('action="/admin/categories/van"');
 assert.ok(categoryForm>0 && !/<form\b/.test(vanPage.slice(categoryForm,vanPage.indexOf('</form>',categoryForm))),'the thresholds form is not nested in the category form');
 assert.match(vanPage,/<input form="vanSizesForm" type="number" min="1" max="2000" name="length_M" value="260"/);
 assert.match(vanPage,/<button form="vanSizesForm"/);
 const thresholds=require('../src/config/serviceTypes').VAN_SIZES.flatMap(s=>[['length_'+s.code,String(s.code==='M'?300:s.length)],['width_'+s.code,String(s.width)],['height_'+s.code,String(s.height)]]);
 assert.equal((await post('/admin/categories/van/size-thresholds',thresholds)).headers.get('location'),'/admin/categories/van?sizesSaved=1');
 assert.match(await get('/admin/categories/van?sizesSaved=1'),/Класс изменился у исполнителей: 1\./);
 assert.equal((await pool.query('SELECT vehicle_size FROM masters WHERE id=$1',[m.id])).rows[0].vehicle_size,'S');
 console.log('PASS: admin multi-service form, needs revision guard, dispatch result rendering, manager assignment, inline script syntax');
 if(process.env.PREVIEW_MULTISERVICE){console.log('PREVIEW '+base+'/admin/masters/'+m.id);console.log('ORDER '+base+'/admin/orders/ui-multi');console.log('MANAGER '+base+'/preview-manager');}
 else {await new Promise(resolve=>server.close(resolve));redis.disconnect();}
})().catch(async e=>{console.error(e);process.exitCode=1;if(server)await new Promise(resolve=>server.close(resolve));redis.disconnect();});
