const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ejs=require('ejs');
const db=require('pg-mem').newDb();db.public.none(fs.readFileSync(path.join(__dirname,'../schema.sql'),'utf8'));
const {Pool}=db.adapters.createPg(),pool=new Pool();
pool.withTransaction=async fn=>{const backup=db.backup();try{return await fn(pool);}catch(e){backup.restore();throw e;}};
const stub=(name,exports)=>require.cache[require.resolve(name)]={exports};
stub('../src/config/db',pool);const redis=new(require('ioredis-mock'))();stub('../src/config/redis',redis);
let sent=0;stub('../src/services/sms.service',{sendOrderNotification:async()=>{sent++;return {ok:true,providerMessageId:'test'};}});
stub('../src/services/telegram.service',{sendLeadToMaster:async()=>false,notifyModerator:async()=>{},updateMessage:async()=>{}});
const billing=require('../src/services/providerBilling.service'),settings=require('../src/services/settings.service');
const orders=require('../src/services/order.service'),masters=require('../src/services/master.service'),audit=require('../src/services/consentLog.service');
const session=require('../src/services/masterSession.service'),controller=require('../src/controllers/master.controller');
const {translate}=require('../src/config/i18n');
(async()=>{
 const master=(await pool.query("INSERT INTO masters(name,phone,master_token,category,is_active,is_subscribed,balance_tetri) VALUES('Billing','+995500000881','billing-master','movers',true,true,5000) RETURNING *")).rows[0];
 await pool.query("INSERT INTO master_services(master_id,service_type,attributes,is_primary) VALUES($1,'movers','{}',true)",[master.id]);
 const order=(await pool.query("INSERT INTO orders(token,phone,description,status,target_categories) VALUES('billing-order','+995500000882','Move a piano','new',ARRAY['movers']) RETURNING *")).rows[0];
 const balance=async()=>Number((await pool.query('SELECT balance_tetri FROM masters WHERE id=$1',[master.id])).rows[0].balance_tetri);
 let state=await billing.state(master.id,'ru');assert.equal(state.accepted,false);
 assert.equal(await orders.notifyMasters(order,'movers',null,50),0);assert.equal(sent,0);
 assert.equal(await masters.revealPhoneForCall(master.id,50,'+995500000882'),null);assert.equal(await balance(),5000);
 let body={accepted:true,digest:state.digest,language:'ru'};
 assert.equal((await billing.accept(master.master_token,{...body,accepted:false})).status,400);
 assert.equal((await billing.accept(master.master_token,{...body,digest:'forged'})).status,409);
 const accepted=await billing.accept(master.master_token,body,{ip:'127.0.0.1'});assert.equal(accepted.status,200);
 assert.equal((await billing.accept(master.master_token,body)).consentLogId,accepted.consentLogId,'double click does not create a second acceptance');
 assert.equal((await billing.state(master.id,'en')).accepted,true,'switching UI language preserves accepted rate');
 const evidence=(await pool.query('SELECT * FROM sms_consent_logs WHERE id=$1',[accepted.consentLogId])).rows[0];
 assert.equal(evidence.ip_address,'127.0.0.1');assert.equal(evidence.metadata.snapshot.lead_price_tetri,50);
 assert.ok(evidence.metadata.snapshot.lead.includes('не открыли'));assert.equal(evidence.metadata.snapshot.language,'ru');
 assert.equal(await orders.notifyMasters(order,'movers',null,50),1);assert.equal(sent,1);
 assert.ok(await masters.revealPhoneForCall(master.id,50,'+995500000882'));assert.equal(await balance(),4900);
 const charge=(await pool.query("SELECT metadata FROM sms_consent_logs WHERE event_type='LEAD_CHARGE_ACCEPTED'")).rows[0].metadata;
 assert.equal(charge.billing_consent_log_id,accepted.consentLogId);
 await settings.setLeadPriceTetri(75);
 assert.equal((await billing.state(master.id,'ru')).accepted,false);assert.equal((await billing.accept(master.master_token,body)).status,409);
 assert.ok((await masters.revealPhoneForCall(master.id,50,'+995500000882')).alreadyOpened,'previously paid contact remains free after rate changes');
 assert.equal(await masters.revealPhoneForCall(master.id,50,'+995500000883'),null,'changed rates block new paid contacts');
 assert.deepEqual(await orders.getDispatchRecipients('movers',null,75),[]);
 await settings.setLeadPriceTetri(50);assert.equal((await billing.state(master.id,'ru')).accepted,false,'restoring old price cannot restore old consent');
 state=await billing.state(master.id,'ru');body={accepted:true,digest:state.digest,language:'ru'};
 const original=audit.recordAction;audit.recordAction=async()=>{throw Error('audit unavailable');};
 await assert.rejects(billing.accept(master.master_token,body),/audit unavailable/);
 audit.recordAction=original;assert.equal((await billing.state(master.id,'ru')).accepted,false);
 assert.equal(await balance(),4900);
 let cookie;await session.start({cookies:{}},{cookie:(key,value)=>{cookie={[key]:value};}},master.master_token);
 const response=()=>({code:200,set(){},status(n){this.code=n;return this;},json(data){this.data=data;return this;}});
 let res=response();await controller.acceptBilling({params:{token:master.master_token},cookies:{},body,lang:'ru',headers:{}},res);assert.equal(res.code,401);
 res=response();await controller.acceptBilling({params:{token:'someone-else'},cookies:cookie,body,lang:'ru',headers:{}},res);assert.equal(res.code,401);
 res=response();await controller.acceptBilling({params:{token:master.master_token},cookies:cookie,body,lang:'ru',headers:{}},res);assert.equal(res.code,200);
 await settings.setLeadPriceTetri(50);assert.equal((await billing.state(master.id,'ru')).accepted,true,'saving same price does not revoke consent');
 for(const lang of ['ka','ru','en']) {
   const billingState={...await billing.state(master.id,lang),accepted:false};
   const html=await ejs.renderFile(path.join(__dirname,'../src/views/partials/provider-billing-consent.ejs'),{master,billingState,t:translate(lang)});
   assert.ok(!/<input[^>]*\schecked(?:\s|>)/.test(html));
   for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);
 }
 console.log('PASS: billing opt-in, both charge gates, exact pricing snapshot, idempotency, stale/reverted rates, audit rollback and session isolation');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>redis.disconnect());
