const assert = require('node:assert/strict');
const fs = require('fs');
const {newDb} = require('pg-mem');
const {parse} = require('../src/config/spokenLanguages');
assert.deepEqual(parse('ka'), ['ka']);
assert.deepEqual(parse(['ru','en','ru']), ['ru','en']);
for (const value of [undefined, [], ['xx'], ['ka', {}], '__proto__']) assert.equal(parse(value), null);
const db = newDb();
const schema = fs.readFileSync(require('path').join(__dirname,'../schema.sql'),'utf8');
db.public.none(schema);
const {Pool} = db.adapters.createPg();
const pool = new Pool();
pool.withTransaction = async fn => {const backup=db.backup();try{return await fn(pool);}catch(e){backup.restore();throw e;}};
require.cache[require.resolve('../src/config/db')] = {exports:pool};
const {registerMaster} = require('../src/services/master.service');
(async () => {
  const args={name:'Languages',phone:'+995500000333',serviceType:'movers'};
  const first=await registerMaster({...args,spokenLanguages:['ka','ru']});
  assert.deepEqual((await pool.query('SELECT spoken_languages FROM masters WHERE id=$1',[first.id])).rows[0].spoken_languages,['ka','ru']);
  await registerMaster({...args,spokenLanguages:['en']});
  assert.deepEqual((await pool.query('SELECT spoken_languages FROM masters WHERE id=$1',[first.id])).rows[0].spoken_languages,['en']);
  await registerMaster(args);
  assert.deepEqual((await pool.query('SELECT spoken_languages FROM masters WHERE id=$1',[first.id])).rows[0].spoken_languages,['en']);
  await assert.rejects(registerMaster({...args,spokenLanguages:['invalid']}));
  const legacy=await registerMaster({...args,phone:'+995500000334'});
  assert.deepEqual(legacy.spoken_languages,[]);
  const ejs=require('ejs');
  for(const file of ['join.ejs','admin/master-detail.ejs']) ejs.compile(fs.readFileSync(require('path').join(__dirname,'../src/views',file),'utf8'));
  const {clientStrings}=require('../src/config/i18n');
  for(const lang of ['ka','ru','en']) assert.ok(clientStrings(lang).join_languages_required);
  console.log('PASS: language validation, persistence, re-registration, legacy profiles, templates and translations');
})().catch(e=>{console.error(e);process.exitCode=1;});
