module.exports = {
  "ru": {
    "catalog_languages": "Языки общения",
    "catalog_language_priority": "Выше — специалисты, говорящие на языке этой страницы.",
    "catalog_only_language": "Только на выбранном языке",
    "catalog_opened": "Вы уже открывали контакты",
    "catalog_language_unknown": "Языки не указаны",
    "contacts_title": "Контакты для клиентов",
    "contacts_hint": "Телефон для звонков остаётся основным. Укажите отдельные номера мессенджеров в международном формате или оставьте поля пустыми. Все каналы открываются клиенту за одно списание; повторное открытие этим клиентом бесплатно.",
    "contacts_same": "Использовать основной номер",
    "contacts_save": "Сохранить контакты и языки",
    "contacts_saved": "Сохранено",
    "contacts_invalid": "Проверьте номера (+код страны), имя Telegram и выберите языки общения.",
    "catalog_empty": "Нет специалистов с такими фильтрами. Попробуйте другой язык или оставьте заявку.",
    "catalog_form_title": "Не хотите обзванивать специалистов?",
    "catalog_form_body": "Опишите задачу один раз: что нужно сделать, где и когда. Укажите язык общения и добавьте фотографии при необходимости. Подробности помогут специалисту оценить работу и задать меньше уточняющих вопросов.",
    "catalog_form_cta": "Описать задачу",
    "catalog_guide_link": "Как это работает",
    "meta_description_index": "Специалисты в Тбилиси: выбирайте услугу и язык общения, звоните или пишите в мессенджер. Оставьте заявку с описанием задачи — размещение бесплатно.",
    "contacts_error": "Не удалось сохранить. Проверьте соединение и повторите попытку."
  },
  "en": {
    "catalog_languages": "Languages spoken",
    "catalog_language_priority": "Providers who speak this page’s language appear first.",
    "catalog_only_language": "Only the selected language",
    "catalog_opened": "You have already opened these contacts",
    "catalog_language_unknown": "Languages not specified",
    "contacts_title": "Customer contact details",
    "contacts_hint": "Your primary number remains your call number. Add separate messenger numbers in international format, or leave them blank. All channels unlock for one charge; repeat access by the same customer is free.",
    "contacts_same": "Use primary number",
    "contacts_save": "Save contacts and languages",
    "contacts_saved": "Saved",
    "contacts_invalid": "Check phone numbers (+country code), Telegram username and select spoken languages.",
    "catalog_empty": "No providers match these filters. Try another language or submit a request.",
    "catalog_form_title": "Prefer not to call around?",
    "catalog_form_body": "Describe your task once: what you need, where and when. Specify your preferred language and add photos if useful. These details help a provider assess the work and reduce follow-up questions.",
    "catalog_form_cta": "Describe your task",
    "catalog_guide_link": "How it works",
    "meta_description_index": "Find providers in Tbilisi by service and spoken language. Call, use an available messenger or describe your task in a free request.",
    "contacts_error": "Could not save. Check your connection and try again."
  },
  "ka": {
    "catalog_languages": "სასაუბრო ენები",
    "catalog_language_priority": "პირველად ჩანს სპეციალისტები, რომლებიც ამ გვერდის ენაზე საუბრობენ.",
    "catalog_only_language": "მხოლოდ არჩეულ ენაზე",
    "catalog_opened": "თქვენ უკვე გახსენით კონტაქტები",
    "catalog_language_unknown": "ენები მითითებული არ არის",
    "contacts_title": "კონტაქტები მომხმარებლებისთვის",
    "contacts_hint": "ძირითადი ნომერი რჩება ზარებისთვის. მიუთითეთ მესენჯერების ცალკე ნომრები საერთაშორისო ფორმატში ან დატოვეთ ველები ცარიელი. ყველა არხი იხსნება ერთი ჩამოჭრით; იმავე მომხმარებლის მიერ განმეორებითი გახსნა უფასოა.",
    "contacts_same": "ძირითადი ნომრის გამოყენება",
    "contacts_save": "კონტაქტებისა და ენების შენახვა",
    "contacts_saved": "შენახულია",
    "contacts_invalid": "შეამოწმეთ ნომრები (+ქვეყნის კოდი), Telegram-ის სახელი და აირჩიეთ სასაუბრო ენები.",
    "catalog_empty": "ამ ფილტრებით სპეციალისტები ვერ მოიძებნა. სცადეთ სხვა ენა ან გაგზავნეთ განაცხადი.",
    "catalog_form_title": "არ გსურთ სპეციალისტებთან სათითაოდ დარეკვა?",
    "catalog_form_body": "ერთხელ აღწერეთ დავალება: რა გჭირდებათ, სად და როდის. მიუთითეთ სასაუბრო ენა და საჭიროებისას დაამატეთ ფოტოები. დეტალები სპეციალისტს სამუშაოს შეფასებაში დაეხმარება და დამატებით კითხვებს შეამცირებს.",
    "catalog_form_cta": "აღწერეთ დავალება",
    "catalog_guide_link": "როგორ მუშაობს",
    "meta_description_index": "იპოვეთ სპეციალისტები თბილისში მომსახურებისა და სასაუბრო ენის მიხედვით. დარეკეთ, გამოიყენეთ მესენჯერი ან უფასოდ განათავსეთ განაცხადი.",
    "contacts_error": "შენახვა ვერ მოხერხდა. შეამოწმეთ კავშირი და სცადეთ ხელახლა."
  }
};
