// Public provider onboarding and account copy. Prices always come from settings.
module.exports = {
  ru: { master_status_page_title: 'xtender.ge — Кабинет исполнителя', master_lead_pending: 'Контакт ещё не открыт',
    provider_intro: 'Получайте заявки и предлагайте свои условия', provider_intro_body: 'Расскажите о своих услугах. После проверки профиля и при достаточном балансе модератор сможет отправлять вам заявки по SMS или в Telegram.',
    provider_prices: 'Как оплачиваются заявки', provider_lead_price: 'Заявка из рассылки', provider_contact_price: 'Показ вашего контакта в каталоге', provider_per_event: 'за событие',
    provider_billing_note: 'Списание с баланса Xtender происходит автоматически за отправленную вам заявку, независимо от звонка или договорённости. Заявку получает группа исполнителей: клиент сам выбирает, с кем работать.',
    provider_catalog_note: 'Если клиент открывает ваш номер через каталог, это отдельное платное событие. Оба тарифа списываются с одного баланса. С телефонного счёта деньги не снимаются.',
    provider_step1: 'Заполните профиль', provider_step2: 'Пройдите проверку', provider_step3: 'Проверьте баланс', provider_step4: 'Получайте заявки',
    provider_services_section: 'Ваши услуги', provider_contact_section: 'Контакт и подтверждение', provider_registration_hint: 'Поля зависят от выбранной услуги. Фото и описание помогут клиенту выбрать вас.',
    provider_description_example: 'Например: работаем вдвоём, перевозим мебель и технику, помогаем с подъёмом. Общаемся на русском и грузинском.',
    provider_districts_note: 'Предпочтительные районы для профиля. Сейчас рассылка подбирается по категории по Тбилиси, без автоматического ограничения этими районами.',
    provider_ready: 'Готовы получать заявки', provider_pending: 'Профиль на проверке', provider_low: 'Пополните баланс для рассылки', provider_disabled: 'Получение заявок недоступно', provider_balance: 'Доступный баланс', provider_channel: 'Канал уведомлений', provider_balance_action: 'Пополнить',
    provider_ready_hint: 'Вы получите уведомление, когда модератор отправит заявку вашей группе. Количество и время поступления заявок зависят от спроса.', provider_pending_hint: 'Данные проверяет модератор. До одобрения заявки не отправляются. Тарифы и реквизиты уже доступны во вкладке «Баланс».', provider_low_hint: 'Профиль одобрен, но средств на следующую заявку недостаточно. Откройте «Баланс», переведите деньги и приложите чек.', provider_disabled_hint: 'Откройте поддержку, чтобы уточнить статус профиля и получения заявок.',
    provider_limits_note: 'Расчёт только для рассылки. Платные открытия номера в каталоге также уменьшают баланс.', provider_telegram_action: 'Настроить уведомления', provider_receipts: 'Ваши чеки', provider_receipts_empty: 'После отправки чека здесь появится статус проверки.',
    receipt_received: 'Получен', receipt_reviewing: 'Проверяется', receipt_credited: 'Зачислено', receipt_rejected: 'Нужно уточнение', provider_receipt_hint: 'Баланс обновляется после проверки перевода модератором. Чек не является автоматическим подтверждением платежа.', provider_history_catalog: 'Показ контакта в каталоге', provider_history_promo: 'Бонус по промокоду', provider_history_other: 'Операция по балансу',
    provider_start_cabinet: 'Открыть кабинет', provider_profile_photo: 'Фото профиля', provider_terms_reminder: 'Перед подтверждением номера проверьте условия оплаты выше.',
    master_lead_contacted: 'нажата кнопка связи', master_status_responded: 'Открывали заявку или кнопки связи', master_status_pending_hint: 'Профиль на проверке. Заявки начнут поступать после одобрения и при достаточном балансе.', join_payment_desc: 'Кабинет уже доступен: там тарифы, статус проверки и реквизиты. Заявки поступают после одобрения при достаточном балансе.', join_success_desc: 'Профиль отправлен модератору. Откройте кабинет, чтобы видеть статус проверки и условия получения заявок.'
  },
  en: { master_status_page_title: 'xtender.ge — Provider account', master_lead_pending: 'Contact not opened yet',
    provider_intro: 'Receive requests. Offer your terms.', provider_intro_body: 'Tell us about your services. Once your profile is approved and your balance is funded, a moderator can send you requests by SMS or Telegram.',
    provider_prices: 'How requests are charged', provider_lead_price: 'Request notification', provider_contact_price: 'Your contact revealed in the directory', provider_per_event: 'per event', provider_billing_note: 'Your Xtender balance is charged automatically for a request sent to you, whether or not you call or agree on a job. A group of providers receives the request; the customer chooses whom to hire.', provider_catalog_note: 'When a customer reveals your number in the directory, it is a separate paid event. Both charges use the same balance. Your mobile phone account is never charged.',
    provider_step1: 'Complete your profile', provider_step2: 'Wait for approval', provider_step3: 'Check your balance', provider_step4: 'Receive requests', provider_services_section: 'Your services', provider_contact_section: 'Contact and verification', provider_registration_hint: 'Fields depend on your service. A photo and description help customers choose.', provider_description_example: 'For example: a crew of two, furniture and appliance transport, help with stairs. We speak English and Georgian.', provider_districts_note: 'Preferred areas for your profile. Requests are currently distributed by category across Tbilisi, without automatically restricting them to these areas.',
    provider_ready: 'Ready to receive requests', provider_pending: 'Profile under review', provider_low: 'Top up to receive requests', provider_disabled: 'Requests unavailable', provider_balance: 'Available balance', provider_channel: 'Notification channel', provider_balance_action: 'Top up', provider_ready_hint: 'You will be notified when a moderator sends a request to your group. Request volume and timing depend on demand.', provider_pending_hint: 'A moderator is reviewing your details. No requests are sent until approval. Prices and bank details are already available under Balance.', provider_low_hint: 'Your profile is approved, but your balance cannot cover the next request. Open Balance, make a transfer and attach the receipt.', provider_disabled_hint: 'Contact support to check your profile and notification status.',
    provider_limits_note: 'Estimate for request notifications only. Paid directory contact reveals also use this balance.', provider_telegram_action: 'Set up notifications', provider_receipts: 'Your receipts', provider_receipts_empty: 'Once you send a receipt, its review status will appear here.', receipt_received: 'Received', receipt_reviewing: 'Under review', receipt_credited: 'Credited', receipt_rejected: 'Clarification needed', provider_receipt_hint: 'Your balance updates after a moderator verifies the transfer. A receipt does not automatically confirm payment.', provider_history_catalog: 'Directory contact reveal', provider_history_promo: 'Promo bonus', provider_history_other: 'Balance transaction', provider_start_cabinet: 'Open dashboard', provider_profile_photo: 'Profile photo', provider_terms_reminder: 'Check the payment terms above before verifying your number.',
    master_lead_contacted: 'contact button clicked', master_status_responded: 'Opened requests or contact buttons', master_status_pending_hint: 'Profile under review. Requests start after approval with sufficient balance.', join_payment_desc: 'Your dashboard is already available with prices, review status and bank details. Requests start after approval with sufficient balance.', join_success_desc: 'Your profile has been sent for review. Open your dashboard to see the status and request notification terms.'
  },
  ka: { master_status_page_title: 'xtender.ge — შემსრულებლის კაბინეტი', master_lead_pending: 'კონტაქტი ჯერ არ გახსნილა',
    provider_intro: 'მიიღეთ განაცხადები და შესთავაზეთ პირობები', provider_intro_body: 'მოგვიყევით თქვენი მომსახურების შესახებ. პროფილის დამტკიცებისა და საკმარისი ბალანსის შემთხვევაში მოდერატორი განაცხადებს SMS-ით ან Telegram-ით გამოგიგზავნით.',
    provider_prices: 'როგორ ირიცხება საფასური', provider_lead_price: 'განაცხადის შეტყობინება', provider_contact_price: 'თქვენი კონტაქტის ნახვა კატალოგში', provider_per_event: 'თითოეულზე', provider_billing_note: 'თქვენთვის გაგზავნილი განაცხადის საფასური Xtender-ის ბალანსიდან ავტომატურად ჩამოიჭრება, ზარის ან შეთანხმების შედეგის მიუხედავად. განაცხადს შემსრულებლების ჯგუფი იღებს; დამკვეთი თავად ირჩევს.', provider_catalog_note: 'კატალოგში თქვენი ნომრის ნახვა ცალკე ფასიანი მოვლენაა. ორივე საფასური ერთი ბალანსიდან იჭრება. მობილურის ანგარიშიდან თანხა არ ჩამოიჭრება.',
    provider_step1: 'შეავსეთ პროფილი', provider_step2: 'დაელოდეთ დამტკიცებას', provider_step3: 'შეამოწმეთ ბალანსი', provider_step4: 'მიიღეთ განაცხადები', provider_services_section: 'თქვენი მომსახურება', provider_contact_section: 'კონტაქტი და დადასტურება', provider_registration_hint: 'ველები მომსახურებაზეა დამოკიდებული. ფოტო და აღწერა დამკვეთს არჩევაში დაეხმარება.', provider_description_example: 'მაგალითად: ვმუშაობთ ორნი, გადაგვაქვს ავეჯი და ტექნიკა, ვეხმარებით სართულზე ატანაში. ვსაუბრობთ ქართულად და რუსულად.', provider_districts_note: 'პროფილისთვის სასურველი უბნები. ამჟამად განაცხადები კატეგორიის მიხედვით მთელ თბილისში ნაწილდება, ამ უბნებით ავტომატური შეზღუდვის გარეშე.',
    provider_ready: 'მზად ხართ განაცხადების მისაღებად', provider_pending: 'პროფილი მოწმდება', provider_low: 'შეავსეთ ბალანსი განაცხადებისთვის', provider_disabled: 'განაცხადების მიღება მიუწვდომელია', provider_balance: 'ხელმისაწვდომი ბალანსი', provider_channel: 'შეტყობინების არხი', provider_balance_action: 'შევსება', provider_ready_hint: 'შეტყობინებას მიიღებთ, როცა მოდერატორი განაცხადს თქვენს ჯგუფს გაუგზავნის. რაოდენობა და დრო მოთხოვნაზეა დამოკიდებული.', provider_pending_hint: 'მოდერატორი თქვენს მონაცემებს ამოწმებს. დამტკიცებამდე განაცხადები არ იგზავნება. ტარიფები და რეკვიზიტები უკვე ხელმისაწვდომია ბალანსის გვერდზე.', provider_low_hint: 'პროფილი დამტკიცებულია, მაგრამ შემდეგი განაცხადისთვის თანხა არ არის საკმარისი. გახსენით ბალანსი, გადარიცხეთ თანხა და დაურთეთ ჩეკი.', provider_disabled_hint: 'პროფილისა და შეტყობინებების სტატუსის გასარკვევად დაუკავშირდით მხარდაჭერას.',
    provider_limits_note: 'გამოთვლა მხოლოდ განაცხადის შეტყობინებებისთვისაა. კატალოგში ნომრის ფასიანი ნახვაც ამ ბალანსს ამცირებს.', provider_telegram_action: 'შეტყობინებების დაყენება', provider_receipts: 'თქვენი ჩეკები', provider_receipts_empty: 'ჩეკის გაგზავნის შემდეგ აქ შემოწმების სტატუსი გამოჩნდება.', receipt_received: 'მიღებულია', receipt_reviewing: 'მოწმდება', receipt_credited: 'ჩარიცხულია', receipt_rejected: 'საჭიროა დაზუსტება', provider_receipt_hint: 'ბალანსი მოდერატორის მიერ გადარიცხვის შემოწმების შემდეგ განახლდება. ჩეკი გადახდას ავტომატურად არ ადასტურებს.', provider_history_catalog: 'კონტაქტის ნახვა კატალოგში', provider_history_promo: 'პრომოკოდის ბონუსი', provider_history_other: 'ბალანსის ოპერაცია', provider_start_cabinet: 'კაბინეტის გახსნა', provider_profile_photo: 'პროფილის ფოტო', provider_terms_reminder: 'ნომრის დადასტურებამდე გაეცანით ზემოთ მოცემულ გადახდის პირობებს.',
    master_lead_contacted: 'კონტაქტის ღილაკზე დაჭერილია', master_status_responded: 'გახსნილი განაცხადები ან კონტაქტის ღილაკები', master_status_pending_hint: 'პროფილი მოწმდება. განაცხადები დამტკიცების შემდეგ, საკმარისი ბალანსით მიიღება.', join_payment_desc: 'კაბინეტი უკვე ხელმისაწვდომია: ტარიფები, შემოწმების სტატუსი და რეკვიზიტები. განაცხადები დამტკიცების შემდეგ, საკმარისი ბალანსით მიიღება.', join_success_desc: 'პროფილი მოდერატორს გაეგზავნა. სტატუსისა და პირობების სანახავად გახსენით კაბინეტი.'
  }
};
